<?php
/*
Author name: Asgar
E-mail ID:   <Your E-mail ID>
Date:        <dd-mm-yyyy>
*/
/////////////////////////////////////////////////////////
//include_once("variables.php");
//include_once("checkLoginStatus.php");
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Corporate Training</title>
    <?php include_once("stylesAndFont.php"); ?>
</head>
<body>
<!-- Mobile bar starts here -->

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <ul> <!-- User class="activeLink" to make links active -->
        <li><a href="#">Home</a></li>
        <li><a href="#">DCent MASS</a></li>
        <li><a href="#">Our Services</a></li>
        <li><a href="#">Student Hub</a></li>
        <li><a href="#">Courses</a></li>
        <li><a href="#">Events</a></li>
        <li><a href="#">Media</a></li>
        <!-- <li><a href="#">Forum</a></li> -->
        <li style="border-bottom:  2px solid #06f;"><a href="#">Contact Us</a></li>
        <!-- <li style="border-bottom:  2px solid #06f;"><a href="#">FAQs</a></li> -->
  </ul>
</div>

<span id="openNavID" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
<!-- Mobile bar ends here -->
     
<div class="mainContainer" id="mainContainer">  <!-- DO NOT REMOVE THIS -->
  <div class="container-fluid">
<!-- MAIN CONTENT STARTS -->







<!-- WRITE MAIN CONTENT HERE -->
<div class="jumbotron jumbotron-fluid" style="margin-top: 10px; background-image: url('images/stock/career counseling.png');
 background-size: 100%; >
  <div class="container">
  <span class="main-heading">  <center><font color="white">CORPORATE TRAINING</font></center></span>
  </div>
</div>


<!-- WRITE MAIN CONTENT HERE -->

<div class="row">
    <div class="col-md-3" >
      <div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/java.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>Java training</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div>
    </div>
    <div class="col-md-3" ><div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/core.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div></div>
    <div class="col-md-3" ><div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/sap.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div></div>
<div class="col-md-3" ><div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/online.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div>
</div>

</div>





<div class="row">
    <div class="col-md-3" >
      <div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/f.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
     
    </div>
  </div>
    </div>
    <div class="col-md-3" ><div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/f.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div></div>
    <div class="col-md-3" ><div style="box-shadow:none;border:none;" class="card" >
    <img class="card-img-top" src="images/f.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div></div>
<div class="col-md-3" ><div style="box-shadow:none;border:none;" class="card" >
    <img  class="card-img-top" src="images/f.jpg" alt="Card image" >
    <div class="card-body">
      <center><h4 class="card-title"><b>John Doe</b></h4>
      <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
      
    </div>
  </div></div>

</div>







<!-- NOTE: Please keep your code clean + readable and add comments -->










<!-- MAIN CONTENT ENDS -->
  </div>
</div>
<?php include_once("script.php"); ?>
</body>
</html>
